<?php
define("BAZARA_MAHAK_SIGNITURE","43BBA4CB-B183-4762-97FF-32E9CD4FCADA");
define("BAZARA_MANA_SIGNITURE", "458E555C-D5C2-423C-9601-78F12832E032");
define("BAZARA_APP_ID", BAZARA_MAHAK_SIGNITURE);
define("BAZARA_CARRIER_PERSON_TYPE", 1);
define("BAZARA_CARRIER_CURRENCY_TYPE", 1);
define("BAZARA_PRODUCT_CATEGORY", 1);
define("BAZARA_PRODUCT_SUB_CATEGORY", 3);
define("BAZARA_PERSON_REGISTER", "register");
define("BAZARA_PERSON_GENERAL", "general");
define("BAZARA_PRODUCT_PERCENT_DISCOUNT", "percent_discount");
define("BAZARA_PRODUCT_PRICE_DISCOUNT", "price_discount");
define("BAZARA_PERSON_ADDRESS_TITLE", "آدرس تحویل");
define("BAZARA_ROLE_COLLABRATE", "همکار");
define("BAZARA_PROPERTY_DATE_TYPE", 5);
define("BAZARA_WCPDF_USER_COLLEGE","همکاران_فروشنده");
define("BAZARA_WCPDF_USER_WHOLESALER","مشتريان_عمده");
define("PLUGIN_DIR_URL", plugin_dir_url(dirname(__FILE__)));


